before_script:
  - echo "Starting Gitlab CI-controlled continuous integration..."

build-campvis:
  tags:
    - linux
  script:
    - mkdir _build
    - cd _build
    - cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Release -DITK_DIR=/var/lib/jenkins/workspace/itk_c++11/_stable -DOpenIGTLink_DIR=/data/jenkins/workspace/open-igt-link/_stable -DCAMPVIS_DEFAULT_ENABLED_MODULES=STABLE_NO_DEPENDENCIES -DCAMPVIS_BUILD_DOXYGEN=false -DCAMPVIS_ENABLE_SCRIPTING=true ../
    - make -j32

doxygen:
  tags:
    - linux
  script:
    - mkdir _build
    - cd _build
    - cmake -G "Unix Makefiles" -DCAMPVIS_BUILD_DOXYGEN=true ../
    - make doc -j16
  artifacts:
    paths:
      - _build/doc/html