before_script:
  - echo "Starting Gitlab CI-controlled continuous integration..."

campvis:
  tags:
    - linux
  script:
    - echo "Starting Build linux-gcc"
    - mkdir _build
    - cd _build
    - cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Release -DITK_DIR=/var/lib/jenkins/workspace/itk_c++11/_stable -DOpenIGTLink_DIR=/data/jenkins/workspace/open-igt-link/_stable -DCAMPVIS_DEFAULT_ENABLED_MODULES=STABLE_NO_DEPENDENCIES -DCAMPVIS_BUILD_DOXYGEN=false -DCAMPVIS_ENABLE_SCRIPTING=true ../
    - make -j32
    - echo "Finished building linux-gcc"
